services:
  db:
    image: postgres
    container_name: electronics_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ElectronicsStore
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: electronics_app
    depends_on:
      - db
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ElectronicsStore
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_JPA_SHOW_SQL: "true"
        SPRING_APPLICATION_NAME: ElectronicsStore
    ports:
      - "8080:8080"